site_name: Candybox
repo_url: https://github.com/RyotaUnzai/candybox
site_url: https://ryotaunzai.github.io/candybox/
site_author: Ryota Unzai / UnPySide.com

theme:
    logo: "siteIcon.png"
    language: ja
    name: material
    palette:
        accent: Green
        primary: Green
    icon:
        repo: fontawesome/brands/github
    features:
        - content.code.annotate
    palette:
      # Palette toggle for light mode
      - scheme: slate
        toggle:
          icon: material/brightness-4 
          name: Switch to dark mode
      # Palette toggle for dark mode
      - scheme: default
        toggle:
          icon: material/brightness-7
          name: Switch to light mode
          name: Switch to system preference

extra:
    social:
        - icon: fontawesome/brands/github-alt
          link: https://github.com/
        - icon: fontawesome/brands/twitter
          link: https://twitter.com/unpyside
        - icon: fontawesome/solid/blog
          link: https://unpyside.com/


plugins:
  - i18n:
      default_language: en
      languages:
        en: English
        ja: 日本語
      nav_translations:
        ja:
          About Extensions: 拡張機能について
          Third Party: サードパーティー


extra_css:
    - https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css

markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - attr_list
    - md_in_html
    - attr_list
    - pymdownx.highlight:
          anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.tabbed:
          alternate_style: true
    - tables
    - footnotes
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
    - md_in_html
    - pymdownx.tasklist:
          custom_checkbox: true
    - pymdownx.snippets
